
server:
  port: 8082

spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: USER-SERVICE
  

resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  